### ISSUE TITLE
htmlInputProcessor parameter is empty

### ISSUE THREAD

**Issue by TitusKirch** [Hanashi/dev.hanashi.wsc.wysiwyg-i18n-form#1]
As you can see in the following image, the htmlInputProcessor parameter for the "description" field is not passed as in the WysiwygFormContainer.

![image](https://user-images.githubusercontent.com/16943133/103352070-7fda3c00-4aa5-11eb-8d60-813b43759816.png)

**Comment by Hanashi** [comment]
It's no bug in this plugin ;)

I fixed it in Simple FAQ with this PR: https://github.com/tkirchDev/dev.tkirch.wsc.faq/pull/57
